minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
savePrefix: ""

allowBuilds:
  "@tailwindcss/oxide": true
overrides:
  fast-uri@>=3.0.0 <3.1.5: ^3.1.5
minimumReleaseAgeExclude:
  - fast-uri@3.1.5
